/*#define b_urine		0
#define b_test1		1
#define b_19200		2
#define b_38400		3
#define b_9600		4
#define b_asa		5
#define b_base		6*/
#define b_19200		0
#define b_38400		1
#define b_9600		2
#define b_asa		3
#define b_base		4
#define b_urine		5
#define b_test1		6
#define b_baud		7
#define b_bbb		8
#define b_bhb		9
#define b_bil		10
#define b_bld		11
#define b_box10		12
#define b_box11		13
#define b_box3		14
#define b_box4		15
#define b_box5		16
#define b_box6		17
#define b_box7		18
#define b_box8		19
#define b_box9		20
#define b_cal		21
#define b_chge1		22
#define b_chge2		23
#define b_check1	24
#define b_check2	25
#define b_clean		26
#define b_color		27
#define b_colset	28
#define b_conv		29
#define b_cre		30
#define b_date1		31
#define b_date2		32
#define b_date3		33
#define b_del1		34
#define b_del2		35
#define b_del3		36
#define b_del4		37
#define b_disab		38
#define b_enab		39
#define b_end		40
#define b_fast		41
#define b_glu		42
#define b_idno		43
#define b_idset1	44
#define b_info1		45
#define b_info2		46
#define b_init		47
#define b_inst		48
#define b_ket		49
#define b_leu		50
#define b_ma		51
#define b_mark		52
#define b_mda		53
#define b_meas		54
#define b_memo1		55
#define b_memo2		56
#define b_memo3		57
#define b_memo4		58
#define b_menu1		59
#define b_menu2		60
#define b_menu3		61
#define b_nic		62
#define b_nit		63
#define b_no		64
#define b_normal	65
#define b_number	66
#define b_off		67
#define b_ph		68
#define b_power		69
#define b_pro		70
#define b_plus		71
#define b_rest1		72
#define b_rest2		73
#define b_rest3		74
#define b_rest4		75
#define b_rest5		76
#define b_send1		77
#define b_send2		78
#define b_send3		79
#define b_send4		80
#define b_seq		81
#define b_seqset	82
#define b_sett1		83
#define b_sg		84
#define b_shut		85
#define b_si		86
#define b_sound		87
#define b_speed		88
#define b_start1	89
#define b_start2	90
#define b_start3	91
#define b_strip		92
#define b_strset	93
#define b_sys1		94
#define b_sys2		95
#define b_test2		96
#define b_test3		97
#define b_time		98
#define b_trubi		99
#define b_turset	100
#define b_unit		101
#define b_uro		102
#define b_view1		103
#define b_view4		104
#define b_yes		105
#define b_view5		106
#define b_arw_l		107
#define b_arw_r		108
#define b_num_c		109
#define b_sett2		110
#define b_numapb	111
#define b_short		112
#define b_long		113
#define b_short		112
#define b_long		113
#define b_macre		114
#define b_r1		115
#define b_r2		116
#define b_r3		117
#define b_graph2	118
#define b_graph3	119
#define b_nicot		120
#define b_nic_r		121
#define b_graph4	122
#define b_bhb_r		123
/*#define b_19200		  0	
#define b_38400		  1	
#define b_9600		  2		
#define b_asa		  3		
#define b_base		  4		
#define b_baud		  5		
#define b_bbb		  6		
#define b_bhb		  7		
#define b_bil		  8		
#define b_bld		  9		
#define b_box10		 10	
#define b_box11		 11	
#define b_box3		 12		
#define b_box4		 13		
#define b_box5		 14		
#define b_box6		 15		
#define b_box7		 16		
#define b_box8		 17		
#define b_box9		 18		
#define b_cal		 19		
#define b_chge1		 20	
#define b_chge2		 21	
#define b_check1	 22		
#define b_check2	 23		
#define b_clean		 24	
#define b_color		 25	
#define b_colset	 26		
#define b_conv		 27		
#define b_cre		 28		
#define b_date1		 29	
#define b_date2		 30	
#define b_date3		 31	
#define b_del1		 32		
#define b_del2		 33		
#define b_del3		 34		
#define b_del4		 35		
#define b_disab		 36	
#define b_enab		 37		
#define b_end		 38		
#define b_fast		 39		
#define b_glu		 40		
#define b_idno		 41		
#define b_idset1	 42		
#define b_info1		 43	
#define b_info2		 44	
#define b_init		 45		
#define b_inst		 46		
#define b_ket		 47		
#define b_leu		 48		
#define b_ma		 49		
#define b_mark		 50		
#define b_mda		 51		
#define b_meas		 52		
#define b_memo1		 53	
#define b_memo2		 54	
#define b_memo3		 55	
#define b_memo4		 56	
#define b_menu1		 57	
#define b_menu2		 58	
#define b_menu3		 59	
#define b_nic		 60		
#define b_nit		 61		
#define b_no		 62		
#define b_normal	 63		
#define b_number	 64		
#define b_off		 65		
#define b_ph		 66		
#define b_power		 67	
#define b_pro		 68		
#define b_plus		 69		
#define b_rest1		 70	
#define b_rest2		 71	
#define b_rest3		 72	
#define b_rest4		 73	
#define b_rest5		 74	
#define b_send1		 75	
#define b_send2		 76	
#define b_send3		 77	
#define b_send4		 78	
#define b_seq		 79		
#define b_seqset	 80		
#define b_sett1		 81	
#define b_sg		 82		
#define b_shut		 83		
#define b_si		 84		
#define b_sound		 85	
#define b_speed		 86	
#define b_start1	 87		
#define b_start2	 88		
#define b_start3	 89		
#define b_strip		 90	
#define b_strset	 91		
#define b_sys1		 92		
#define b_sys2		 93		
#define b_test1		 94	
#define b_test2		 95	
#define b_test3		 96	
#define b_time		 97		
#define b_trubi		 98	
#define b_turset	 99		
#define b_unit		100		
#define b_urine		101	
#define b_uro		102		
#define b_view1		103	
#define b_view4		104	
#define b_yes		105		
#define b_view5		106	
#define b_arw_l		107	
#define b_arw_r		108	
#define b_num_c		109		
#define b_sett2		110	
#define b_numapb	111		
#define b_short		112	
#define b_long		113	//file	110
#define b_macre		114
#define b_r1		115
#define b_r2		116
#define b_r3		117
#define b_graph2	118
#define b_graph3	119
#define b_nicot		120
#define b_nic_r		121
#define b_graph4 	122
#define b_bhb_r		123*/

#define MSBXS 	36 		//- XS_OFFSET/2
#define MSBYS	360
#define MSBXE	234 	//- XS_OFFSET/2
#define MSBYE	380
#define MSBSC	WHT		//검사박스
#define MSBBC	RED		//후진  
#define MSBEC	YEL		//진행  
#define MSBCC	BLU		//분석

#define CABXS	45
#define CABYS	168
#define CABXE	225
#define CABYE	178
#define SYBXS	CABXS
#define SYBYS	227
#define SYBXE	CABXE
#define SYBYE	237

#ifdef _DSP_C_
u8 bmp_head[0x600];

void lcd_test(void);
void dsp_first(void);
void dsp_standby(void);
void dsp_seq_set(void);
void blink_seqno(void);
void dsp_idno_set(void);
void blink_idno(void);
void dsp_strip_sel(void);
void dsp_strip8line(void);
void blink_strip(u8 lno);
void dsp_color_sel(void);
void dsp_color_no(void);
void blink_color(void);
void dsp_turbi_sel(void);
void dsp_turbi_no(void);
void blink_turbi(void);
void dsp_menu_home(void);
void dsp_date_time(void);
void out_date_time(void);
void dsp_sys_chk(void);
void dsp_sys_info(void);
void dsp_memory(void);
void dsp_view_no(void);
void dsp_result_store(u16 sno);
void dsp_result(u16 sno);
void dsp_send_no(void);
void dsp_delete_no(void);
void dsp_setting(void);
void dsp_format(void);
void dsp_system(void);
void dsp_change1(void);
void dsp_change2(void);
void dsp_change3(void);
void blink_pr_dgt(void);
void dsp_down(void);
void dsp_poff(void);
void dsp_measure(void);
void dsp_measure_time(u16 dt);
void dsp_novalid(void);
void blink_send(void);
void blink_send_no(void);
void blink_delete(u16 dly);
void dsp_pr_set(void);
void blink_endno(u16 eno);
void blink_srtno(u16 eno);
void dsp_prog_ng(void);
void dsp_prog_ok(void);
void dsp_pass(void);

#else
extern u8 bmp_head[0x600];

extern void lcd_test(void);
extern void dsp_first(void);
extern void dsp_standby(void);
extern void dsp_seq_set(void);
extern void blink_seqno(void);
extern void dsp_idno_set(void);
extern void blink_idno(void);
extern void dsp_strip_sel(void);
extern void dsp_strip8line(void);
extern void blink_strip(u8 lno);
extern void dsp_color_sel(void);
extern void dsp_color_no(void);
extern void blink_color(void);
extern void dsp_turbi_sel(void);
extern void dsp_turbi_no(void);
extern void blink_turbi(void);
extern void dsp_menu_home(void);
extern void dsp_date_time(void);
extern void out_date_time(void);
extern void dsp_sys_chk(void);
extern void dsp_sys_info(void);
extern void dsp_memory(void);
extern void dsp_view_no(void);
extern void dsp_result_store(u16 sno);
extern void dsp_result(u16 sno);
extern void dsp_send_no(void);
extern void dsp_delete_no(void);
extern void dsp_setting(void);
extern void dsp_format(void);
extern void dsp_system(void);
extern void dsp_change1(void);
extern void dsp_change2(void);
extern void dsp_change3(void);
extern void blink_pr_dgt(void);
extern void dsp_down(void);
extern void dsp_poff(void);
extern void dsp_measure(void);
extern void dsp_measure_time(u16 dt);
extern void dsp_novalid(void);
extern void blink_send(void);
extern void blink_send_no(void);
extern void blink_delete(u16 dly);
extern void dsp_pr_set(void);
extern void blink_endno(u16 eno);
extern void blink_srtno(u16 eno);
extern void dsp_prog_ng(void);
extern void dsp_prog_ok(void);
extern void dsp_pass(void);
#endif